name: Sync on DOMCloud
on:
  workflow_dispatch: {}
  release:
    type: [published]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >
            {
              "commands": [
                "git pull",
                "composer install --no-dev --optimize-autoloader",
                "php artisan migrate --force",
                "killall -u $USER"
              ]
            }
          
          